repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-ast
    - id: name-tests-test
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
      - id: gitleaks
- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: bash -c 'pytest'
      language: system
      pass_filenames: false
      always_run: true
